$(document).ready(function(){
	$(".original").on("click",function(e){
		e.preventDefault();
		$(".sertificates-js").show()
	});
	$(".not-active").on("click",function(e){
		e.preventDefault();
	});
});